apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pepr-root
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/cmwylie19/pepr-with-argo
    targetRevision: HEAD
    path: k8s/apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
