apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapps.application.pepr.dev
spec:
  group: application.pepr.dev
  names:
    kind: WebApp
    plural: webapps
    singular: webapp
    shortNames:
      - wa
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: WebAppSpec defines the desired state of WebApp
              properties:
                language:
                  type: string
                  description: Langauge of the web application (english or spanish)
                replicas:
                  type: number
                  description: Number of replicas for the deployment
                theme:
                  type: string
                  description: Color theme of the web application (dark or light)
              required:
                - language
                - replicas
                - theme
            status:
              type: object
              description: WebAppStatus defines the observed state of WebApp
              properties:
                conditions:
                  type: array
                  description: Conditions describing the current state
                  items:
                    type: object
                    description: Condition contains details for one aspect of the current state of
                      this API Resource.
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                        description: lastTransitionTime is the last time the condition transitioned from
                          one status to another. This is not guaranteed to be
                          set in happensBefore order across different conditions
                          for a given object. It may be unset in some
                          circumstances.
                      reason:
                        type: string
                        description: reason contains a programmatic identifier indicating the reason for
                          the condition's last transition. If this value is
                          empty, it should be treated as "incomplete".
                      status:
                        type: string
                        description: status of the condition, Pending, Ready, Failed
                      observedGeneration:
                        type: number
                        description: observedGeneration represents the .metadata.generation that the
                          condition was set based upon. For instance, if
                          .metadata.generation is currently 12, but the
                          .status.conditions[x].observedGeneration is 9, the
                          condition is out of date with respect to the current
                          state of the instance.
                    required:
                      - lastTransitionTime
                      - reason
                      - status
                      - observedGeneration
      subresources:
        status: {}
